//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mymins {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class LayoutSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LayoutSettings defaultInstance = ((LayoutSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LayoutSettings())));
        
        public static LayoutSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecminID {
            get {
                return ((bool)(this["visPanelSpecminID"]));
            }
            set {
                this["visPanelSpecminID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelMinMins {
            get {
                return ((bool)(this["visPanelMinMins"]));
            }
            set {
                this["visPanelMinMins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visLabelMinPlus {
            get {
                return ((bool)(this["visLabelMinPlus"]));
            }
            set {
                this["visLabelMinPlus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visFlowLayoutPanelMinEdit {
            get {
                return ((bool)(this["visFlowLayoutPanelMinEdit"]));
            }
            set {
                this["visFlowLayoutPanelMinEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelMinEditAddDel {
            get {
                return ((bool)(this["visPanelMinEditAddDel"]));
            }
            set {
                this["visPanelMinEditAddDel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelMinName {
            get {
                return ((bool)(this["visPanelMinName"]));
            }
            set {
                this["visPanelMinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelMinMember {
            get {
                return ((bool)(this["visPanelMinMember"]));
            }
            set {
                this["visPanelMinMember"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelMinMindatID {
            get {
                return ((bool)(this["visPanelMinMindatID"]));
            }
            set {
                this["visPanelMinMindatID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visLabelSpecPlus {
            get {
                return ((bool)(this["visLabelSpecPlus"]));
            }
            set {
                this["visLabelSpecPlus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecDetails {
            get {
                return ((bool)(this["visPanelSpecDetails"]));
            }
            set {
                this["visPanelSpecDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecHeight {
            get {
                return ((bool)(this["visPanelSpecHeight"]));
            }
            set {
                this["visPanelSpecHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecLength {
            get {
                return ((bool)(this["visPanelSpecLength"]));
            }
            set {
                this["visPanelSpecLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecWidth {
            get {
                return ((bool)(this["visPanelSpecWidth"]));
            }
            set {
                this["visPanelSpecWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecUnits {
            get {
                return ((bool)(this["visPanelSpecUnits"]));
            }
            set {
                this["visPanelSpecUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecWeight {
            get {
                return ((bool)(this["visPanelSpecWeight"]));
            }
            set {
                this["visPanelSpecWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecwUnits {
            get {
                return ((bool)(this["visPanelSpecwUnits"]));
            }
            set {
                this["visPanelSpecwUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecRepair {
            get {
                return ((bool)(this["visPanelSpecRepair"]));
            }
            set {
                this["visPanelSpecRepair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecArtificial {
            get {
                return ((bool)(this["visPanelSpecArtificial"]));
            }
            set {
                this["visPanelSpecArtificial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecAppraisal {
            get {
                return ((bool)(this["visPanelSpecAppraisal"]));
            }
            set {
                this["visPanelSpecAppraisal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecRating {
            get {
                return ((bool)(this["visPanelSpecRating"]));
            }
            set {
                this["visPanelSpecRating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecTransparent {
            get {
                return ((bool)(this["visPanelSpecTransparent"]));
            }
            set {
                this["visPanelSpecTransparent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecCrystal {
            get {
                return ((bool)(this["visPanelSpecCrystal"]));
            }
            set {
                this["visPanelSpecCrystal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelSpecComment {
            get {
                return ((bool)(this["visPanelSpecComment"]));
            }
            set {
                this["visPanelSpecComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visLabelConPlus {
            get {
                return ((bool)(this["visLabelConPlus"]));
            }
            set {
                this["visLabelConPlus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelFromContact {
            get {
                return ((bool)(this["visPanelFromContact"]));
            }
            set {
                this["visPanelFromContact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelFromConAddDel {
            get {
                return ((bool)(this["visPanelFromConAddDel"]));
            }
            set {
                this["visPanelFromConAddDel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConName {
            get {
                return ((bool)(this["visPanelConName"]));
            }
            set {
                this["visPanelConName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConCountry {
            get {
                return ((bool)(this["visPanelConCountry"]));
            }
            set {
                this["visPanelConCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConState {
            get {
                return ((bool)(this["visPanelConState"]));
            }
            set {
                this["visPanelConState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConCounty {
            get {
                return ((bool)(this["visPanelConCounty"]));
            }
            set {
                this["visPanelConCounty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConCity {
            get {
                return ((bool)(this["visPanelConCity"]));
            }
            set {
                this["visPanelConCity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConAddress {
            get {
                return ((bool)(this["visPanelConAddress"]));
            }
            set {
                this["visPanelConAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConType {
            get {
                return ((bool)(this["visPanelConType"]));
            }
            set {
                this["visPanelConType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConGPSlat {
            get {
                return ((bool)(this["visPanelConGPSlat"]));
            }
            set {
                this["visPanelConGPSlat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConGPSlon {
            get {
                return ((bool)(this["visPanelConGPSlon"]));
            }
            set {
                this["visPanelConGPSlon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConPhone {
            get {
                return ((bool)(this["visPanelConPhone"]));
            }
            set {
                this["visPanelConPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConEmail {
            get {
                return ((bool)(this["visPanelConEmail"]));
            }
            set {
                this["visPanelConEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConWeb {
            get {
                return ((bool)(this["visPanelConWeb"]));
            }
            set {
                this["visPanelConWeb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConComment {
            get {
                return ((bool)(this["visPanelConComment"]));
            }
            set {
                this["visPanelConComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelConMindatID {
            get {
                return ((bool)(this["visPanelConMindatID"]));
            }
            set {
                this["visPanelConMindatID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visFlowLayoutPanelExpoEdit {
            get {
                return ((bool)(this["visFlowLayoutPanelExpoEdit"]));
            }
            set {
                this["visFlowLayoutPanelExpoEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visExpoDatePartsBox {
            get {
                return ((bool)(this["visExpoDatePartsBox"]));
            }
            set {
                this["visExpoDatePartsBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelAcquTo {
            get {
                return ((bool)(this["visPanelAcquTo"]));
            }
            set {
                this["visPanelAcquTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visAcquDatePartsBox {
            get {
                return ((bool)(this["visAcquDatePartsBox"]));
            }
            set {
                this["visAcquDatePartsBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelAcquPrice {
            get {
                return ((bool)(this["visPanelAcquPrice"]));
            }
            set {
                this["visPanelAcquPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelAcquType {
            get {
                return ((bool)(this["visPanelAcquType"]));
            }
            set {
                this["visPanelAcquType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visPanelAcquExposure {
            get {
                return ((bool)(this["visPanelAcquExposure"]));
            }
            set {
                this["visPanelAcquExposure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool visAcquDataGridView {
            get {
                return ((bool)(this["visAcquDataGridView"]));
            }
            set {
                this["visAcquDataGridView"] = value;
            }
        }
    }
}
